### ISSUE TITLE
Found issues on a few URLs

### ISSUE THREAD

**Issue by skanga** [dvcoolarun/web2pdf#1]
1. I tried it on a github homepage (like this one https://github.com/d60/twikit) and it did NOT show most of the text
2. On another page the apostrophe's are totally botched which make the page ugly. Each one is replaced with black diamond with a "?" inside it. This is the URL https://www.theverge.com/2024/2/3/24058476/tesla-hazardous-waste-suit-settlement-california

And here is what it looks like:

<img width="566" alt="image" src="https://github.com/dvcoolarun/web2pdf/assets/1558197/e9ba9207-3aa9-48f6-8e34-0bd61fe7ddca">

**Comment by dvcoolarun** [comment]
I'm not able to replicate the issue with the Verge article. Please try again.

Also, regarding the GitHub repo print issue, most of the text is coming from React server rendering.

I'll need to look into it in more detail.
