### ISSUE TITLE
use containers

### ISSUE THREAD

**Issue by kfedora** [dvcoolarun/web2pdf#3]
Looks like this needs pango. Can this be a docker container so it comes with everything it needs? 

> WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

> OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'

once I got past that, I got 
> OSError: cannot load library 'pangoft2-1.0-0': pangoft2-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pangoft2-1.0-0'

once I got past that I got 

```
$ python main.py https://gamersnexus.net/features-deep-dive/how-ram-made-automated-binning-manufacturing-burn-testing-factory-tours
Traceback (most recent call last):
  File "/home/[username]/src/py/web2pdf/main.py", line 7, in <module>
    from readability import Document
ImportError: cannot import name 'Document' from 'readability' (/home/[username]/.local/share/virtualenvs/web2pdf-ZHT1wjR3/lib/python3.9/site-packages/readability/__init__.py)
```

**Comment by dvcoolarun** [comment]
Same Error :: https://github.com/Kozea/WeasyPrint/issues/1448

Yes, I want to make this accessible for everyone without the need to require installation of packages.

In that sense, I'm considering:

Creating a standalone executable
Distributing as a package
Containerization

I might go with the standalone executable approach for now.

**Comment by hposca** [comment]
FYI, using a dockerfile like this one:

```Dockerfile
FROM python:3.9

WORKDIR /src

RUN pip install -U pipenv

COPY Pipfile Pipfile.lock ./

RUN pipenv install --system

COPY . .

ENTRYPOINT [ "python", "/src/main.py" ]
```

Works, **BUT** I had to remove the `requests` library from `Pipfile` and `Pipfile.lock`.
Don't know if due to, or despite it, the page I tested it (https://stackoverflow.com/questions/38321055/importerror-no-module-named-readability) ended up being a almost blank 4 pages pdf :cry: 

---

```bash
docker build -t web2pdf .
docker run -ti -v $(pwd):/src web2pdf                                                                                                               │
```

**Comment by dvcoolarun** [comment]
@kfedora I recently removed the readability package in response to the issue you encountered. I believe this change will resolve your problem.

https://github.com/dvcoolarun/web2pdf/commit/a912649f8953402fff14636c9edd7c8766dba5b6
