### ISSUE TITLE
Cloud Storage

### ISSUE THREAD

**Issue by tijko** [dvcoolarun/web2pdf#6]
Provide options to save documents to cloud accounts (i.e. Google-Drive).

I've been working in some options to make API calls to save documents to my Google Drive account.

**Comment by dvcoolarun** [comment]
The main agenda of this project is to build PDF files from URLs. 

Since this functionality is not supported in our context, I'll be closing this issue.

**Comment by tijko** [comment]
Oh I didn't realize that was all this was intended to do.

I had a look at the code and it is barely functioning with regards to displaying images within the documents.  Perhaps that needs some work.
