### ISSUE TITLE
Image is breaking when its actual height beyond the size of the page

### ISSUE THREAD

**Issue by naivecoder786** [dvcoolarun/web2pdf#8]
Current output:
![image](https://github.com/dvcoolarun/web2pdf/assets/117038957/ec710c8d-2201-4530-a2dd-b7b67b033e0d)

Expected output:
![image](https://github.com/dvcoolarun/web2pdf/assets/117038957/cbe89445-a1ab-492c-809f-0c95a651814f)

Attaching the output pdf for reference which had breaking of image as a serious issue. 
[print.pdf](https://github.com/dvcoolarun/web2pdf/files/14396203/print.pdf)

**Comment by naivecoder786** [comment]
To repro this issue use this web page link which was to be converted to pdf-
https://alpha.learnersbucket.com/s/preview/courses/658bee23e4b0174a3cb6c294/articles/65927298e4b049a44b13a24e/get

**Comment by dvcoolarun** [comment]
Due to these particular rendering issues, I have not packaged this. You seem like a web developer.

In the main file, there is a `css` file where you can change the output however you want. 

you specify a specific height for the images?

**Comment by naivecoder786** [comment]
@dvcoolarun actually I did try that but I wasnt able to get it to work properly. Below are my changes, even after adding this the image seems to break
![image](https://github.com/dvcoolarun/web2pdf/assets/117038957/da0dd65c-ba38-43d3-a3b8-a730263040d3)
